### ISSUE TITLE
未授权数据包存在BUG

### ISSUE THREAD

**Issue by Superhero-zero** [smxiazi/xia_Yue#11]
![1704726202731](https://github.com/smxiazi/xia_Yue/assets/66772820/7d196fa4-c162-440f-9344-54c702be4abd)
![image](https://github.com/smxiazi/xia_Yue/assets/66772820/14bd1b2a-5c31-47a4-a8e1-3045a4524d02)

**Comment by smxiazi** [comment]
1.4版本已修复
