### ISSUE TITLE
同接口重复测试

### ISSUE THREAD

**Issue by gsf111** [smxiazi/xia_Yue#3]
存在一个bug，同样的接口会重复测试不同cookie，只要请求路径传入的ID不同他就会重复测试，实际上是同一个接口，如果没越权，就不可能会成功了
![image](https://user-images.githubusercontent.com/59310045/222651949-0698c70a-725d-49fa-b1c3-3620f8c51ab6.png)
![image](https://user-images.githubusercontent.com/59310045/222652009-b9fe7307-9b89-41b3-a045-f75fb727da38.png)

**Comment by smxiazi** [comment]
已优化，请下载1.2版本。
