### ISSUE TITLE
未授权调整建议

### ISSUE THREAD

**Issue by ghost** [smxiazi/xia_Yue#4]
版本：
BurpSuite v2022.9.5
xia Yue v1.2_jdk8
未授权部分的头部认证信息只会去除第一个关键字的样子。

少部分情况下，请求头里是有多个值需要去除的。建议如果关键字在未授权列表里，都进行删除或替换。

瞎哥出品，必属精品！！！

**Comment by smxiazi** [comment]
啊…… 不会呀，你未授权里面填入多个要删除的信息，如果有，他都会删除呀。

**Comment by smxiazi** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/30351807/223008976-56a7ff8b-50a3-44fd-b6a8-776105cea28a.png">

有删除多个

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/30351807/223009107-0257c2f3-cb60-4df2-8559-bfd4af1fce3f.png">
