### ISSUE TITLE
未授权数据包问题

### ISSUE THREAD

**Issue by ccc996** [smxiazi/xia_Yue#9]
今天测试好像发现了未授权的小BUG，原始包：
![image](https://github.com/smxiazi/xia_Yue/assets/70511523/2dc9fe64-dbe5-4e19-b055-5989c487d3a6)
未授权包：
![image](https://github.com/smxiazi/xia_Yue/assets/70511523/cfc80d1d-c802-4061-ba3b-3ca245567a3d)
以上插件功能使用都正常，但只有这个接口成功
其他接口，原始包：
![image](https://github.com/smxiazi/xia_Yue/assets/70511523/83ed9dfd-ddc3-414e-b89d-f7ea8df6a27a)
未授权包：
![image](https://github.com/smxiazi/xia_Yue/assets/70511523/da7e765d-730a-40c5-ae13-f866a02b4d16)
Mip-Console仍然存在，未匹配上移除

**Comment by SkinAir** [comment]
+1
